app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|   resource
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['prefix' => 'api'], function () {
    Route::controller('posts', 'Api\PostController');
});
Route::auth();
Route::get('/welcome', 'HomeController@index');
Route::resource('catalogue', 'CatalogueController');
Route::resource('tag', 'TagController');
Route::resource('media', 'MediaController', ['only' => ['store', 'show', 'destroy']]);
Route::resource('post', 'PostController');
Route::resource('profile', 'ProfileController', ['only' => ['index', 'show']]);
Route::get('catalogue/createpost/{id}', 'PostController@catalogueCreate');
//Api for FaceBook ,Google ,Twitter , LinkedIn  
Route::get('auth/{id}', 'Auth\LoginWithController@redirectToProvider');
Route::get('auth/{id}/callback', 'Auth\LoginWithController@handleProviderCallback');

app/Models/Posts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * Class Posts
 * @package App\Models
 */
class Posts extends Model
{


    /**
     * @var string
     */
    protected $table = 'posts';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'catalogue_id',
        'body',
        'media_id'
    ];
    protected $dates=['created_at','updated_at'];
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\User', 'user_id', 'id');
    }

    /**
     * Get Tags which his related with Post
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany('App\Models\Tags','tag_post','post_id','tag_id');
    }
    /**
     * Get catalogue which his related with Post
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function catalogue()
    {
        return $this->belongsTo('App\Models\Catalogues', 'catalogue_id', 'id');
    }
    /**
     * Get media which his related with Post
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function media()
    {
        return $this->belongsTo('App\Models\Media', 'media_id', 'id');
    }

    /**
     * Return true if is the owner the post
     * @return bool
     */
    public function ismy()
    {
        return Auth::user()->id == $this->user_id;
    }
    

}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'email', 'password', 'name'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Add name Attribute
     * @return string
     */
    public function getNameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    /**
     * The relationship between media and users
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function media()
    {
        return $this->belongsTo('App\Models\Media', 'media_id', 'id');
    }

    /**
     * Return image path
     * @return string
     */
    public function getPathImageAttribute()
    {
        if (isset($this->media)) {
            return $this->media->full_path;
        } else {
            return 'src/img/default.png';
        }
    }

    /**
     * @return mixed
     */
    public function getPostsPAttribute()
    {
        return ($this->posts()->paginate(5, ['*'], 'p'));
    }

    /**
     * The Relationship with Posts models
     *
     */
    public function posts()
    {
        return $this->hasMany('App\Models\Posts', 'user_id', 'id');
    }

    /**
     * @param $name
     */
    public function setNameAttribute($name)
    {
        $names = explode(' ', $name);
        $this->first_name = $names[0];
        $this->last_name = $names[1];
    }
}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Requests;
use App\Models\Posts;

class PostController extends ApiController
{
    /**
     * @return \Illuminate\Http\JsonResponse
     */
    public function getIndex()
    {
        $paginate = Posts::with(['user', 'media', 'catalogue', 'user.media'])->orderBy('created_at', 'desc')->paginate(3, ['*'], 'p');
        $json = [];
        $json['paginate'] = $this->paginateArray($paginate);
        $json['data'] = $this->reViewsPosts($paginate->items());
        return $this->respone($json);
    }

    /**
     * @param $post
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View|null
     */
    private function reViewsPosts($post)
    {
        if (!$post) return null;
        if (is_array($post)) {
            $posts = $post;
            $view = array();
            foreach ($posts as $post) {
                $view []= ''.view('post.includes.unit', ['post' => $post]);
            }
            return $view;
        } else {
            return view('post.includes.unit', ['post' => $post]);
        }
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Models\Posts;
use App\Models\Tags;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class PostController extends Controller
{
    /**
     * PostController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('post.index', ['posts' => Posts::orderBy('created_at','desc')->take(3)->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'catalogue_id' => 'required|numeric|exists:catalogues,id',
            'media_id' => 'numeric|exists:media,id',
        ]);

        $post = Auth::user()->posts()->create($request->all());
        $tags = $request->input('tags');
        if (isset($tags)) {
            $this->AttachTags($post, $tags);
        }
        return redirect('post/' . $post->id);
    }

    /**
     * Add tag to his post
     * @param $post
     * @param $tag_list
     */
    private function AttachTags($post, $tag_list)
    {
        $IDs = [];
        foreach ($tag_list as $tag) {
            if (is_numeric($tag)) {
                $IDs[] = $tag;
            } else {
                $IDs[] = Tags::create(['name' => $tag])->id;
            }
        }
        $post->tags()->sync($IDs);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('post.show', ['post' => Posts::findOrFail($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('post.edit', ['post' => Posts::findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'catalogue_id' => 'required|numeric|exists:catalogues,id',
            'media_id' => 'numeric|exists:media,id',
        ]);
        $post = Auth::user()->posts()->where('id',$id)->first();
        if(is_null($post))return response('404 Page not found',404);
        $tags = $request->input('tags');
        if (isset($tags)) {
            $this->AttachTags($post, $tags);
        }
        return redirect('post/' . $post->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Posts::findOrFail($id);
        if ($post->ismy()) {
            $media = $post->media;
            if (isset($media)) {
                $media->delete();
            }
            $post->delete();
            return redirect('/post')->with('done', ['title' => 'Delete Done!', 'body' => '']);
        }
        return response('Unauthorized', 401);
    }

    /** create with cataloge defult value
     * @param $id
     * @return $this
     */
    public function catalogueCreate($id)
    {
        return view('post.create')->with('select_default', $id);
    }
}

resources/views/post/includes/formcou.blade.php
<script src="{{asset('src/js/image_operation.js')}}">
</script>
<div class="col-xs-8 col-sm-8 col-md-8 col-lg-8 col-md-offset-2">
    @if(isset($update)&&isset($post))
        {!! Form::model($post,['class'=>'form-horizontal', 'action'=>['PostController@update',$post->id],'id'=>'postForm','method'=>'PATCH']) !!}
    @else
        {!! Form::open(['class'=>'form-horizontal', 'action'=>['PostController@store'],'id'=>'postForm']) !!}
    @endif
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title col-md-9 ">
                <h4>{{isset($update)&&isset($post)?'Editing Post':'New Post'}}</h4>
            </div>
            <div class="form-group{{ $errors->has('catalogue_id') ? ' has-error' : '' }}">
                <div class="col-md-3">
                    @if(isset($select_default))
                        {!! Form::select('catalogue_id',App\Models\Catalogues::pluck('name','id'),$select_default
                       ,['class'=>'form-control']) !!}
                    @else
                        {!! Form::select('catalogue_id',App\Models\Catalogues::pluck('name','id'),old('catalogue_id')
                        ,['class'=>'form-control']) !!}
                    @endif
                    @if ($errors->has('catalogue_id'))
                        <span class="help-block"><strong>{{ $errors->first('catalogue_id') }}</strong></span>
                    @endif
                </div>
                <br>
            </div>
        </div>
        <div class="panel-body">
            <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
                {!! Form::textarea('body',old('body') ,['class'=>'form-control',
                'id'=>'body','placeholder'=>'Enter what you think?']) !!}
                @if ($errors->has('body'))
                    <span class="help-block"><strong>{{ $errors->first('body') }}</strong></span>
                @endif
            </div>
            <div class="form-group{{ $errors->has('tags') ? ' has-error' : '' }}">
                <label for="tags" class="col-md-1 control-label">Tags:</label>
                @if(isset($update)&&isset($post))
                    {!! Form::select('tags[]',App\Models\Tags::pluck('name','id'),$post->tags->pluck('id')->toArray(),['class'=>'form-control','id'=>'tags','multiple']) !!}
                @else
                    {!! Form::select('tags[]',App\Models\Tags::pluck('name','id'),old('tags'),['class'=>'form-control','id'=>'tags','multiple']) !!}
                @endif
                @if ($errors->has('tags'))
                    <span class="help-block"><strong>{{ $errors->first('tags') }}</strong></span>
                @endif
            </div>
            <div class="panel-footer" id="uploaded-img">
                @if(isset($update)&&isset($post)&&isset($post->media))
                    <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                        <div class="thumbnail">
                            <button type="button" class="close" onclick="UnloadImage(this,'{{$post->media->id}}')">×</button>
                            <img src="/{{$post->media->full_path}}" class="img-thumbnail"
                                 alt="Uploaded image" id="uploaded-img" accept="image/*"></div>
                    </div>
                @else
                    <input type="file" class="btn-file" name="img" id="button_upload"
                           onchange="UploadImage(this)" accept="image/*"/>
                @endif
            </div>
        </div>
        {{--Final footer --}}
        <div class="panel-footer">
            <div class="form-group">
                <div class="col-sm-10">
                    {!! Form::submit('Done',['class'=>'btn btn-']) !!}
                </div>
            </div>
            <br>
        </div>
    </div>
    {!! Form::close() !!}
</div>
<script>
    $('#tags').select2(
            {
                placeholder: "Enter your tags",
                allowClear: true,
                tags: true,
                createTag: function (params) {
                    var term = $.trim(params.term);
                    if (term === '') {
                        return null;
                    }
                    return {
                        id: term,
                        text: term,
                    }
                },
            }
    );
</script>

resources/views/post/includes/unit.blade.php
<div class="panel panel-primary" id="parant-post">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-7">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <img class="img-circle img-thumbnail icon_img" src="{{asset($post->user->path_image)}}"/>
                </div>
                <br>
                <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
                    <h3 class="panel-title"><a href="{{asset('profile/?email='.$post->user->email)}}">{{$post->user->name}}</a>
                        @<a class="btn-primary"
                            href="{{asset('catalogue/'.$post->catalogue->id)}}">{{$post->catalogue->name}}</a>
                    </h3></div>
            </div>
            <div class="col-md-4">
                <p>{{$post->created_at->toCookieString()}}</p>
            </div>
            @if($post->ismy())
                <div class="col-md-1">
                    <div class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="glyphicon glyphicon-pencil" style="color:white" title="Setting"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{{asset('post/'.$post->id.'/edit')}}">Edit</a></li>
                            <li id="catalogue_delete">
                                {!! Form::open(['action'=>['PostController@destroy',$post->id]
                                ,'method'=>'DELETE','id'=>'delete'.$post->id]) !!}
                                {!! Form::close() !!}
                                <a data-toggle="modal" data-target="#myModal"
                                   onclick="deletePost('{{$post->id}}')" id="button">Delete</a>
                            </li>
                        </ul>
                    </div>
                </div>
            @endif
            {{--continus--}}
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            @if(isset($post->media_id)&&!is_null($post->media_id))
                <div class="">
                    <blockquote>
                        {{$post->body}}
                    </blockquote>
                    <div class="thumbnail">
                        <a data-toggle="modal" href="#img-model" id="show-post-model"> <img id="show-post-model" class="img-rounded" src="/{{$post->media->full_path}}"/></a>
                    </div>
                </div>
            @else
                {{$post->body}}
            @endif
            <div class="col-lg-5 col-md-10">
                @if(isset($post->tags )&&count($post->tags )>0)
                    @foreach($post->tags as $tag)
                        <a href="{{asset('/tag/'.$tag->name)}}">
                            <kbd class="btn-primary">{{$tag->name}}</kbd>
                        </a>
                    @endforeach
                @endif
            </div>
        </div>
    </div>

</div>

resources/views/post/includes/updated_post.blade.php
 <div id="queue_posts">
        @if(count($posts)<1)
            <h1>Not his the posts</h1>
        @else
            @each('post.includes.unit',$posts,'post')
        @endif
    </div>
<script type="application/javascript">
    function deletePost(id) {
        document.getElementById('delete_button').setAttribute('onclick', 'document.getElementById(\'delete' + id + '\').submit()');
    }
</script>
<div class="row">
    <div class="col-xs-4 col-lg-offset-4">
        <a class="btn btn-block btn-primary" id="more"><span
                    class="glyphicon glyphicon-plus-sign"></span><b>Show More</b><span class="badge"
                                                                                       id="number-post">{{count($posts)}}</span></a>
    </div>
</div>
<script>
    /**************************************************************************/
    var paginateJson = null;
    $('a#more').click(function () {
        if (!paginateJson) {
            var data = {
                p: "2"
            }
        } else {
            var data = {
                p: paginateJson.currentPage + 1
            }
        }
        $.ajaxSetup({headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')}});
        $.ajax({
                    url: '/api/posts',
                    type: 'GET',
                    dataType: 'json',
                    data: data
//                        statusCode: {}
                }
        ).done(function (json) {
            for (var i = 0; i < json.data.length; i++) {
                $('div#queue_posts').append(json.data[i]);
            }
            if (json.data.length < 3) {
                $('#more').css('display', 'none');
            }
            paginateJson = json.paginate;
        }).fail(function (xhr, status, errorThrown) {
            alert("Sorry, there was a problem!");
        });
    });
    $('a#show-post-model').click(function (event) {
        var me = event.target;
        $('#post-img-model').html(me.outerHTML);
        var main = (me).closest('div#parant-post');
        $('#post-body-model').html(main.outerHTML);
    });
</script>
<div class="modal" id="img-model" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true">
    <div class="modal-dialog" role="document" style="">
        <div class="modal-content">
            <div class="modal-body" id="post-model-body" style="background-color: transparent">
                <a type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></a>
                <div class="row">
                    <div class="col-xs-12" id="post-body-model">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>