app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|   resource
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['prefix' => 'api'], function () {
    Route::controller('posts', 'Api\PostController');
});
Route::auth();
Route::get('/welcome', 'HomeController@index');
Route::resource('catalogue', 'CatalogueController');
Route::resource('tag', 'TagController');
Route::resource('media', 'MediaController', ['only' => ['store', 'show', 'destroy']]);
Route::resource('post', 'PostController');
Route::resource('profile', 'ProfileController', ['only' => ['index', 'show']]);
Route::get('catalogue/createpost/{id}', 'PostController@catalogueCreate');
//Api for FaceBook ,Google ,Twitter , LinkedIn  
Route::get('auth/{id}', 'Auth\LoginWithController@redirectToProvider');
Route::get('auth/{id}/callback', 'Auth\LoginWithController@handleProviderCallback');

app/Models/Catalogues.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Catalogues
 * @package App\Models
 */
class Catalogues extends Model
{
    /**
     * @var string
     */
    protected $table = 'catalogues';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description'];

    /**
     * Relationship in Catalogue and Posts
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function posts()
    {
        return $this->hasMany('App\Models\Posts', 'catalogue_id', 'id');
    }

    /**
     * @return mixed
     */
    public function getPostsPAttribute()
    {
      return ($this->posts()->paginate(5,['*'],'p'));
    }
}

app/Http/Controllers/CatalogueController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Models\Catalogues;
use Illuminate\Http\Request;

class CatalogueController extends Controller
{
    /**
     * CatalogueController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', ['except' => 'index']);
    }

    /**
     * Display a listing of the Catalogue .
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('catalogue.index')->with('catalogs', Catalogues::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('catalogue.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:catalogues|max:50',
            'description' => 'required'
        ]);
        $catalogue = Catalogues::create($request->all());
        return redirect('/catalogue/' . $catalogue->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
       // $catalogue = Catalogues::with('posts')->find($id);
        return view('catalogue.show')->with('catalogue', Catalogues::with('posts')->find($id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('catalogue.update')->with('catalogue', Catalogues::find($id));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $catalogue = Catalogues::find($id);
        $rules = [];
        if ((trim($catalogue->name) == trim($request->input('name')))) {

        } else {
            $rules = ['name' => 'required|unique:catalogues|max:50',
                'description' => 'required'];
        }
        $this->validate($request, $rules);
        $catalogue->update($request->all());
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Catalogues::findOrFail($id)->delete();
        return redirect('/catalogue')->with('done', ['title' => 'Delete Done', 'body' => '']);
    }
}

resources/views/catalogue/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                	  <div class="panel-heading">
                			<h3 class="panel-title">
                              New Catalogue
                            </h3>
                	  </div>
                	  <div class="panel-body">
                			@include('catalogue.includes.formcou',['form'=>'create'])
                	  </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/catalogue/index.blade.php
@extends('layouts.app')

@section('content')
    @include('includes.alert')
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-10   ">
                <a class="btn btn-primary" href="{{asset('catalogue\create')}}">
                    <span class="glyphicon glyphicon-plus" title="Add Catalogue"></span>
                    Add new Catalogue
                </a>
            </div>
        </div>
        <br>
        <div class="row">
            @each('catalogue.includes.unit',$catalogs,'catalogue')
        </div>

    </div>
    <script type="application/javascript">
        function deleteCatalogue(id) {
            document.getElementById('delete_button').setAttribute('onclick', 'document.getElementById(\'delete' + id + '\').submit()');
        }
    </script>
@endsection

resources/views/catalogue/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1 class="panel-title">
                            {{$catalogue->name}}
                        </h1>
                    </div>
                    <div class="panel-body">
                        {{$catalogue->description}}
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6">
                <div class="col-xs-1 col-xs-offset-9">
                    <a class="btn btn-primary" href="{{asset('catalogue/createpost/'.$catalogue->id)}}"><span
                                class="glyphicon glyphicon-plus"></span>Add new Post</a>
                </div>
                <div class="row"></div>
                <div class="panel panel-collapse">
                    @include('post.includes.updated_post',['posts'=>$catalogue->posts_p])
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/catalogue/update.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">
                            Update Catalogue
                        </h3>
                    </div>
                    <div class="panel-body">
                        @include('catalogue.includes.formcou',['form'=>'update'])
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection